package com.arcsoft.supervisor.cluster.net;

import java.util.EventListener;

/**
 * An object that registers to be notified of events generated by a
 * <code>TcpServer</code> object.
 * 
 * @author fjli
 */
public interface TcpConnectionListener extends EventListener {

	/**
	 * Notifies this <code>TcpConnectionListener</code> that the TcpServer
	 * accept a new request and the connection is created.
	 * 
	 * @param connection - the created connection
	 */
	void connectionCreated(TcpConnection connection);

}
